version: "3.9"

services:
  database:
    build: ./mysql
    restart: unless-stopped
    environment:
      - ./database/.env

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - ./backend/.env

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - ./frontend/.env

volumes:
  mysql_data: {}