server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://MYSQL8010.site4now.net/db_aa9cb6_mysql  #jdbc:mysql://mysql-container:3306/electronics_project
    username: aa9cb6_mysql
    password: maianh@1234
#    url: jdbc:mysql://localhost:3306/electronics_project
#    username: root
#    password: 123456
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
application:
  security:
    jwt:
      secret-key: e61ff531bcdb5c96be3df4b390233264e35d1453b1ced0b162a70de2173e712e
      expired: 86400000 #a month
      refresh-token:
        expired: 604800000 #a day
  doc:
    version: 1.0.0
    title: Electronics Project
    description: Backend API
    license:
      name: MIT
      url: https://opensource.org/licenses/MIT
    server:
      url: http://localhost:8080
      description: Local server
  file-upload:
    images:  /static/images/
    files:  /static/files/




